services:
  postgres:
    image: "postgres:18.1"
    container_name: "postgres"
    volumes:
      - pg_data:/data/18
    environment:
      PGDATA: "$POSTGRES_DATA"
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_DB: "$POSTGRES_DB"
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pg_data:
    driver: local
